package com.se1605.model.invoice.easyinvoice;


public class Content {
    public String Key;
    public String ArisingDate;
    public Object ComFax;
    public String ComName;
    public String ComTaxCode;
    public String ComAddress;
    public Object ComPhone;
    public Object ComEmail;
    public Object ComBankNo;
    public Object ComBankName;
    public Object Ikey;
    public Object ParentName;
    public String InvoiceName;
    public String InvoicePattern;
    public String SerialNo;
    public int InvoiceNo;
    public String PaymentMethod;
    public Object CusCode;
    public String CusName;
    public int CusTaxCode;
    public Object CusPhone;
    public String CusAddress;
    public Object CusBankName;
    public Object CusBankNo;
    public int Total;
    public int VATAmount;
    public int Amount;
    public String AmountInWords;
    public Object Buyer;
    public int VATRate;
    public Object Note;
    public Object CusEmails;
    public String amountInWordsL2;
    public Products Products;
    public int GrossValue;
    public int GrossValue0;
    public int VatAmount0;
    public int GrossValue5;
    public int VatAmount5;
    public int GrossValue10;
    public int VatAmount10;
    public int GrossValueNDeclared;
    public int VatAmountNDeclared;
    public int GrossValueContractor;
    public int VatAmountContractor;
    public int ExchangeRate;
    public String CurrencyUnit;
    public String PortalLink;
    public boolean Hidden;
    public String SignDate;
    public String Id;
    public String text;
}
